###### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [1]:
import numpy as np

In [17]:
def numpy_array ( N ):
    return np.arange(N-1, -1, -1)

In [18]:
numpy_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

###### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [20]:
np.diag(np.arange(10-1, -1, -1))

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
def diag_count (N):
    array1 = np.diag(np.arange(N-1, -1, -1))
    i = 0
    list1 = []
    for line in array1:
        column = line[0+i]
        i += 1
        list1.append(column)
    return sum(list1)

In [41]:
diag_count(10)

45

###### Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [42]:
from numpy import linalg

In [43]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])

In [44]:
b = np.array( [4, 12, -3] )

In [45]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

###### Задача 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

In [49]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [48]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats


In [56]:
def most_similar_users(users_stats, next_user_stats):
    cos_distances = np.dot( users_stats, next_user_stats )/(np.linalg.norm( users_stats )*np.linalg.norm( next_user_stats ))
    max_cos_distance = max(np.dot( users_stats, next_user_stats )/(np.linalg.norm( users_stats )*np.linalg.norm( next_user_stats )))

    res = np.where(cos_distances==max_cos_distance)
    user_number = np.concatenate(res).tolist()
    print(f'Самые похожие пользователи {user_number}, с косинусным расстоянием {max_cos_distance}')

In [57]:
most_similar_users(users_stats, next_user_stats)

Самые похожие пользователи [1, 3], с косинусным расстоянием 0.2344036154692477
